# ??????
server.port=8080
server.error.include-message=always

# ???????????
logging.level.com.example.feedback=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# ??????????? ??????? (??? ?????????)
spring.web.resources.static-locations=classpath:/static/,file:./frontend/
spring.web.resources.add-mappings=true